version: '3.7'
services:
  alerts_go:
    build:
      context: ./alerts
    ports:
      - "8082:8082"
    networks:
      - alerts_network
    depends_on:
      - prometheus

  prometheus:
    build:
      context: ./prometheus
    ports:
      - "9090:9090"  # Expose Prometheus on port 9090 on the host
    command:
      - --storage.tsdb.path=/prometheus
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-admin-api
      - --web.enable-lifecycle
    volumes:
      - ./prometheus/data:/prometheus  # Persistent volume for Prometheus data
    networks:
      - alerts_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboard:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/config:/etc/grafana/custom
    user: root
    env_file:
      - ./grafana/config/config.env
    depends_on:
      - prometheus
    networks:
      - alerts_network

networks:
  alerts_network: