version: '3.7'
services:
  alerts_go:
    build:
      context: ./alerts
    ports:
      - "8082:8082"
    networks:
      - alerts_network
    depends_on:
      - prometheus

  prometheus:
    build:
      context: ./prometheus
    ports:
      - "9090:9090"  # Expose Prometheus on port 9090 on the host
    volumes:
      - ./prometheus/data:/prometheus  # Persistent volume for Prometheus data
    networks:
      - alerts_network

networks:
  alerts_network: