services:
  alerts_go:
    build:
      context: ./alerts
    ports:
      - "8082:8082"
    volumes:
      - ./alerts/config:/root/config  # Persistent volume for Prometheus data
    networks:
      - alerts_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboard:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/config:/etc/grafana/custom
    user: root
    env_file:
      - ./grafana/config/config.env
    networks:
      - alerts_network
      - external_mysql_network

networks:
  alerts_network:
  external_mysql_network:
    name: local_mysql_network
    external: true
